# A. Data Indexing and Selection in Series


In [1]:
import pandas as pd
import numpy as np

## A.1 Series as a Dictionary

In [13]:
# let us create a series object 
series_1 = pd.Series(data= np.random.random(10), 
                     index=[i for i in range(1,11)])
print(f'The series is:\n{series_1}')

# just like a dict we can access the keys and the values of the series
print(f'The keys of the series are: {series_1.keys()}')
print(f'The values of the series are:{series_1.values}')

The series is:
1     0.942116
2     0.296167
3     0.788731
4     0.412677
5     0.698284
6     0.962335
7     0.100298
8     0.150475
9     0.331060
10    0.268245
dtype: float64
The keys of the series are: Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')
The values of the series are:[0.94211627 0.29616736 0.78873082 0.41267672 0.69828427 0.96233481
 0.1002984  0.15047548 0.33106028 0.26824487]


In [14]:
# items of the series - same as the items() method used in dict
print(f'The items of the series (list of (key,value) tuples): {series_1.items()}')
'''
The output you're seeing indicates that series_1.items() returns a zip object. This object is an iterator that lazily produces (index, value) pairs from the series. However, it does not directly produce a list unless explicitly converted.
'''

# let us explicitly mention this 
# Get the items and convert to a list
items = list(series_1.items())

print(f'The items of the series (list of (key, value) tuples): {items}')

The items of the series (list of (key,value) tuples): <zip object at 0x0000028173B54D00>
The items of the series (list of (key, value) tuples): [(1, 0.9421162670736947), (2, 0.2961673634226166), (3, 0.7887308203176896), (4, 0.4126767241943542), (5, 0.6982842663181421), (6, 0.9623348126494431), (7, 0.10029840370907839), (8, 0.15047548063503646), (9, 0.3310602758043256), (10, 0.2682448658669687)]


In [15]:
# like dict, you can use key to access the elements of the series 
series_1[3]

0.7887308203176896

In [16]:
# you can add elements to the series by defining a new key/index
series_1[11] = 0.9876
print(series_1)

1     0.942116
2     0.296167
3     0.788731
4     0.412677
5     0.698284
6     0.962335
7     0.100298
8     0.150475
9     0.331060
10    0.268245
11    0.987600
dtype: float64


## A.2 Series as a One-Dimensional Array

If you have a Series with an **explicit index starting from 1**, slicing like `series[1:3]` will use the **implicit integer positions, not the explicit index**.

**Solution:**
- You can use `.loc[]` or `.iloc[]`to make your intent explicit:
    - Use `.loc[]` to **slice using the explicit (labeled) index**.
    - Use `.iloc[]` to slice using the **implicit (integer) index**.

In [22]:
# slicing with explicit index 
print(f'The first three items using explicit indexing : \n{series_1.loc[1:3]}')

# slicing with implicit index
print(f'The first three items with implicit indexing : \n{series_1.iloc[:3]}')

The first three items using explicit indexing : 
1    0.942116
2    0.296167
3    0.788731
dtype: float64
The first three items with implicit indexing : 
1    0.942116
2    0.296167
3    0.788731
dtype: float64


The behavior you observe is because the `.loc[]` indexer in pandas **includes the end label** in the slicing range, following a **closed interval** logic `[start:end]`. This is in contrast to Python’s default slicing behavior (like with lists or `.iloc[]`), which uses a **half-open interval** `[start:end)`.

Here’s a breakdown:

### Key Differences:
1. **`.loc[]` (label-based slicing)**:
   - Includes the end label in the slice (`[start:end]`).
   - This is consistent with the behavior of operations on labels in pandas.
   - Example: `series.loc[1:3]` includes both 1, 2, and 3 as it uses the labels.

2. **`.iloc[]` (position-based slicing)**:
   - Excludes the end position in the slice (`[start:end)`).
   - Example: `series.iloc[:3]` includes positions 0, 1, and 2, stopping before position 3.

---

### Example to Clarify:

```python
import pandas as pd

# Create a Series with an explicit index starting from 1
series_1 = pd.Series([10, 20, 30, 40], index=[1, 2, 3, 4])

print("Original Series:")
print(series_1)

# Explicit index slicing with .loc[]
print("\nSlicing with .loc[] (explicit indexing, closed interval):")
print(series_1.loc[1:3])  # Includes the end label (index 3)

# Implicit index slicing with .iloc[]
print("\nSlicing with .iloc[] (implicit indexing, half-open interval):")
print(series_1.iloc[:3])  # Excludes the end position (position 3)
```

### Output:

```plaintext
Original Series:
1    10
2    20
3    30
4    40
dtype: int64

Slicing with .loc[] (explicit indexing, closed interval):
1    10
2    20
3    30
dtype: int64

Slicing with .iloc[] (implicit indexing, half-open interval):
1    10
2    20
3    30
dtype: int64
```

---

### Why `.loc[]` Includes the End Label:
The `.loc[]` behavior aligns with pandas’ philosophy of working with labeled data:
- When working with labels, it’s often more intuitive for users to think in terms of "from label X to label Y" and expect both labels to be included.

This behavior ensures clarity and reduces off-by-one errors when working with labeled indices.

In [ ]:
# fancy indexing - pass as a list of index in the loc 
print(f'The first, third and seventh element are:\n{series_1.loc[[1,3,7]]}')

The first, third and seventh element are:
1    0.942116
3    0.788731
7    0.100298
dtype: float64


In [ ]:
# boolean logic and masking in the Series object - just like the NumPy arrays 

# consider the following series
series = pd.Series(data=[12,45,67,88,34,54,76,99,7,8,10])

# find the mean of the series 
mean_series = np.mean(series)
print(f"The mean of the series is {mean_series}")

# create the boolean array 
bool_series = series > mean_series
print("Boolean Series (True when value greater than mean): ")
print(bool_series)

# use this boolean series to filer the original series 
print("Using the boolean series to filter the original :")
print(series.loc[bool_series]) # use loc[] indexer for masking

The mean of the series is 45.45454545454545
Boolean Series (True when value greater than mean): 
0     False
1     False
2      True
3      True
4     False
5      True
6      True
7      True
8     False
9     False
10    False
dtype: bool
Using the boolean series to filter the original :
2    67
3    88
5    54
6    76
7    99
dtype: int64


# B. Data Indexing and Selection in DataDrame


In [27]:
area = pd.Series({'California': 423967, 'Texas': 695662, 
                  'Florida': 170312, 'New York': 141297, 
                  'Pennsylvania': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505, 
                 'Florida': 21538187, 'New York': 20201249, 
                 'Pennsylvania': 13002700})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [28]:
# accessing each series of the dataframe 
area_series = data['area']
print(area_series)

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64


In [29]:
# add a new fature to the dataframe 
data['density'] = data['pop']/data['area']
data

area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

## B.1 DataFrame as a 2D NumPy array

In [32]:
data_numpy = data.to_numpy()
print(f'The NumPy array of the dataframe is:\n{data_numpy}')

data_numpy_T = data.T # transposes the dataframe 
print(f'The transposed array converted to NumPy array is:\n{data_numpy_T.to_numpy()}')

The NumPy array of the dataframe is:
[[4.23967000e+05 3.95382230e+07 9.32577842e+01]
 [6.95662000e+05 2.91455050e+07 4.18960717e+01]
 [1.70312000e+05 2.15381870e+07 1.26463121e+02]
 [1.41297000e+05 2.02012490e+07 1.42970120e+02]
 [1.19280000e+05 1.30027000e+07 1.09009893e+02]]
The transposed array converted to NumPy array is:
[[4.23967000e+05 6.95662000e+05 1.70312000e+05 1.41297000e+05
  1.19280000e+05]
 [3.95382230e+07 2.91455050e+07 2.15381870e+07 2.02012490e+07
  1.30027000e+07]
 [9.32577842e+01 4.18960717e+01 1.26463121e+02 1.42970120e+02
  1.09009893e+02]]


Using the `iloc` indexer, we can index a dataframe as if it is a simple 2D NumPy array!

In [ ]:
# say I want the 1st and third row of area and pop
data.iloc[[0,2],[0,1]] # note use the implicit index only!

area       pop
California  423967  39538223
Florida     170312  21538187

In [45]:
# when we use the loc indexer, we have to use the explicit indexing 
data.loc[:'Florida',['area','pop']]

area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [41]:
# we can use the loc[] indexer to mask
data.loc[data['density']<120, ['pop','density']]

pop     density
California    39538223   93.257784
Texas         29145505   41.896072
Pennsylvania  13002700  109.009893

In [44]:
# we can modify any value 
data.iloc[0,1] = 39600000
print(data)

# back to the original 
data.loc['California','pop'] = 39538223
print(f'\n{data}')

                area       pop     density
California    423967  39600000   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

                area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893


END!